version: '3.3'
services:

  frontend:
    image: striki23/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  
  backend:
    image: striki23/foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - .env
    depends_on:
      - db  
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend 
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
  db_volume:
