# Generated by Django 4.2.1 on 2023-06-12 19:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=7, samples=None
            ),
        ),
    ]
