# Generated by Django 4.2.1 on 2023-06-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=500, verbose_name="Пароль"),
        ),
    ]
